### ISSUE TITLE
estlintConfig load order with baseConfig vs configFile

### ISSUE THREAD

**Issue by tinyroy** [telus/telus-standard#69]
In version 3.0.2, the `eslintConfig` changed from `baseConfig` to `configFile`.

https://github.com/telus/telus-standard/pull/66/files#diff-078d658abc1b24cecf58ef7cbf06e56663a252ce82b15689975cf88cc9f1ac15R13

It prevents anyone from using `.eslintrc.*` locally to override the rules or anything because `configFile` takes precedence.

Reference: https://eslint.org/docs/developer-guide/nodejs-api#cliengine

Can this be reverted?

**Comment by Nitin-TELUS** [comment]
Hi @tinyroy, Thanks for reaching out, we'll take a look and update you ASAP.

**Comment by afzal-telus** [comment]
Hi @tinyroy,
We’ve taken a look on this but reverting the changes is not possible because this package will not work with **npx** with **baseConfig**. As there was lots of security vulnerabilities before major release so we’ve updated most of the dependencies and configuration accordingly.
As this packages is using [standard-engine](https://www.npmjs.com/package/standard-engine) so we’ve followed the document to resolve those error. Please let me know if there is any alternative option for this.
Thanks.

**Comment by afzal-telus** [comment]
Hi @tinyroy ,
We’re looking for your suggestion here, as mentioned above reverting the changes is not possible.

**Comment by Nitin-TELUS** [comment]
Hi @tinyroy, As there is no update so we're closing this issue.

**Comment by tinyroy** [comment]
sorry, did not see this till now.

I've tested with `baseConfig` and it works with `standard-engine`. The entire eslintConfig object just gets passed to eslint.

**Comment by Nitin-TELUS** [comment]
Hi @tinyroy, We've tested and after the installation as dev dependency it's working as expected but when we use this as npx it'll unable to get the object. That was the main reason to update this object. It would be very helpful if you can give it a try with npx.

**Comment by codyzu** [comment]
Hello, we are having the same problem with UDS and it's preventing us from upgrading to the latest version of `telus-standard` we have some custom config files, but they are no longer taking precedence over the built-in config and described by @tinyroy 

@Nitin-TELUS what is the exact problem with npx, if I set my devDependency to `@telus/telus-standard@3.0.1` everything is fine, if I run `npx @telus/telus-standard` still runs fine. Once I upgrade to `v3.0.2` both are broken due to our config having lower precedence over the built-in config :cry: .

We have custom config mostly due to making `telus-standard` work with the common practices around react-native.

**Comment by Nitin-TELUS** [comment]
Hi @codyzu,

The problem is with the configFile path available inside the config.  https://github.com/telus/telus-standard/blob/master/options.js#L12.

We've tried all the scenarios to validate it, but it's not working with both (npx and custom config). This problem occurred once eslint introduced some breaking changes with v7. We've updated it because of lots of security vulnerabilities. 

The only difference between v3.0.1 vs v3.0.2 is, first one will work with custom config and the second one with npx. Please let me know if you've any suggestions on this, we'll introduce to overcome this problem.

**Comment by codyzu** [comment]
Thanks for your quick response.

* Can you share the exact steps to reproduce the problem with npx. I can't reproduce the problem myself.
* It is [mentioned above](https://github.com/telus/telus-standard/issues/69#issuecomment-886744490) that you followed the steps laid out in standard-engine, do you have a link to an issue there that describes the problem?

I hope we can find a good solution. Thanks for you support :pray:

**Comment by Nitin-TELUS** [comment]
@codyzu let's connect on slack.
